# Generated by Django 5.0.3 on 2024-03-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
