# Generated by Django 5.0.3 on 2024-04-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_subscription_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='started',
            field=models.DateTimeField(null=True),
        ),
    ]
