# Generated by Django 5.0.3 on 2024-04-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bot_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
