# Generated by Django 5.0.3 on 2024-04-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='option',
            name='slug',
            field=models.SlugField(default='', max_length=30),
        ),
    ]
