# Generated by Django 5.0.3 on 2024-04-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_option_description_option_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='slug',
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
